[project]
name = "comfyui_sata_utilitynode"
description = "ComfyUI utility nodes collection providing features like prompt machine, resolution machine, and upscale machine to enhance workflow efficiency."
version = "1.2.0"
license = "MIT"

[project.urls]
Repository = "https://github.com/SatadalAI/SATA_UtilityNode"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "SatadalAI"
DisplayName = "SATA_UtilityNode"
Icon = ""